const fs=require('fs'),vm=require('vm'),assert=require('assert');
const T=require('../vendor/three.min.js');
const sandbox={THREE:T,BrickGrid:require("../brick-grid.js"),window:{},document:{createElement(){return{width:128,height:128,getContext(){return{fillRect(){},fillText(){}}}}}}};
let source=fs.readFileSync('brick-renderer.js','utf8').replace('  window.BrickRenderer=BrickRenderer;','  window.BrickRenderer=BrickRenderer;window.test={brick,cabin,chicken,geometryCache,STUD_PITCH,attachWheels,spinWheels};');
assert(!source.includes('#f3f1d5'),'Grass renderer must not draw white flower spots');
vm.runInNewContext(source,sandbox);
const {brick,cabin,chicken,geometryCache,STUD_PITCH}=sandbox.window.test;
assert.equal(STUD_PITCH,.25);
const parts=[];chicken(parts);
const bodyStud=geometryCache.get('stud:0.075');assert(bodyStud);
const grass=[];brick(grass,0,0,0,4,4,1,'#4f9d38');
assert.equal(grass.filter(p=>p.g===bodyStud).length,16);
const centers=grass.filter(p=>p.g===bodyStud).map(p=>p.matrix.elements[12]);
const xs=[...new Set(centers)].sort((a,b)=>a-b);
for(let i=1;i<xs.length;i++)assert(Math.abs(xs[i]-xs[i-1]-.25)<1e-8);
const renderer=Object.create(sandbox.window.BrickRenderer.prototype);renderer.scene=new T.Scene();
renderer.createRow({y:0,type:'grass',trees:[],flowers:[],items:[]});
assert(!geometryCache.has('stud:0.15'),'Grass must not use oversized studs');
const raft=renderer.createRow({y:1,type:'water',trees:[],flowers:[],items:[{x:0,length:3.5}]}).moving[0].node;
assert(Math.abs(new T.Box3().setFromObject(raft).getSize(new T.Vector3()).x-3.488)<1e-5);
const cabinParts=[];cabin(cabinParts,0,0,0,'#ffbb00');
const positions=geometryCache.get('cabin-glass').attributes.position;
const bottom=[],top=[];
for(let i=0;i<positions.count;i++)(positions.getY(i)<.01?bottom:top).push([positions.getX(i),positions.getZ(i)]);
const bounds=points=>[Math.min(...points.map(p=>p[0])),Math.max(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[1]))];
const b=bounds(bottom),t=bounds(top);
assert(t[0]>b[0]&&t[1]<b[1],'Both windshields slope toward the roof along travel direction');
assert.equal(t[2],b[2]);assert.equal(t[3],b[3]);
console.log('PASS shared chicken/grass stud geometry and pitch');
console.log('PASS actual grass mesh uses standard studs');
console.log('PASS raft width and seams align to brick grid');
console.log('PASS windshields slope along the vehicle length, not width');

const {attachWheels,spinWheels}=sandbox.window.test;
const left=new T.Group();attachWheels(left,[[0,-.4,.23],[0,.4,.23]]);left.rotation.y=Math.PI;
spinWheels(left,-.22);assert(Math.abs(left.rollingWheels[0].rotation.z+1)<1e-8);
const right=new T.Group();attachWheels(right,[[0,-.4,.23]]);spinWheels(right,.44);
assert(Math.abs(right.rollingWheels[0].rotation.z+2)<1e-8);
assert.equal(left.rollingWheels[1].rotation.z,left.rollingWheels[0].rotation.z);
const groundParts=[];brick(groundParts,.375,-.125,-.135,4,4,1,'#4f9d38');
const groundCenters=groundParts.filter(p=>p.g===bodyStud).map(p=>[p.matrix.elements[12],-p.matrix.elements[14]]);
assert(groundCenters.some(([x,y])=>Math.abs(x)<1e-9&&Math.abs(y)<1e-9));
assert(groundCenters.every(([x,y])=>Math.abs(x/.25-Math.round(x/.25))<1e-9&&Math.abs(y/.25-Math.round(y/.25))<1e-9));
const streamed={y:2,type:'grass',trees:[],flowers:[],items:[],chunks:new Map([[96,{start:96,end:104,trees:[],flowers:[]}]])};
const row=renderer.createRow(streamed);assert.equal(row.chunks.size,1);
const bound=new T.Box3().setFromObject(row.static);assert(bound.min.x<100&&bound.max.x>100);
streamed.chunks=new Map([[-104,{start:-104,end:-96,trees:[],flowers:[]}]]);
renderer.syncRow(row,streamed);assert.equal(row.chunks.size,1);assert(row.chunks.has(-104));
console.log('PASS wheel rotation uses distance and axle radius in both directions');
console.log('PASS ground studs include the chicken standing coordinates');
console.log('PASS renderer streams and removes terrain chunks at distant coordinates');
